# cd $WORK_PATH 目录下,先运行的 public.h -> 设备.h -> scripts/feeds install -a
# 定义部分以及需要添加对应APP必须的文件
device_name='MiRouter'                                                      # 自定义设备名
wifi_name="RMWiFi"                                                          # 自定义Wifi 名字
lan_ip='192.168.2.1'                                                        # 自定义Lan Ip地址
utc_name='Asia\/Shanghai'                                                   # 自定义时区
ver_name='D200513'                                                          # 版本号
delete_bootstrap=false                                                      # 是否删除默认主题 true 、false
default_theme='luci-theme-argon_new'                                        # 默认主题 结合主题文件夹名字
theme_argon='https://github.com/sypopo/luci-theme-argon-mc.git'             # 主题地址
openClash_url='https://github.com/vernesong/OpenClash.git'                  # OpenClash包地址
adguardhome_url='https://github.com/rufengsuixing/luci-app-adguardhome.git' # adguardhome 包地址
lienol_url='https://github.com/Lienol/openwrt-package.git'                  # Lienol 包地址
vssr_url_rely='https://github.com/jerrykuku/lua-maxminddb.git'              # vssr lua-maxminddb依赖
vssr_url='https://github.com/jerrykuku/luci-app-vssr.git'                   # vssr地址
vssr_plus_rely='https://github.com/Leo-Jo-My/my.git'                        # vssr_plus 依赖
vssr_plus='https://github.com/Leo-Jo-My/luci-app-vssr-plus.git'             # vssr_plus 地址
filter_url='https://github.com/destan19/OpenAppFilter.git'                  # AppFilter 地址
smartdns_url='https://github.com/pymumu/openwrt-smartdns'                   # SmartDNS运行程序
smartdnsapp_url='https://github.com/pymumu/luci-app-smartdns.git'           # SmartDNS-App
serverchan_url='https://github.com/tty228/luci-app-serverchan.git'          # serverchan备份包

#下面是执行具体操作

echo "修改机器名称"
sed -i "s/OpenWrt/$device_name/g" package/base-files/files/bin/config_generate

echo "修改wifi名称"
sed -i "s/OpenWrt/$wifi_name/g" package/kernel/mac80211/files/lib/wifi/mac80211.sh

echo "设置lan ip"
sed -i "s/192.168.1.1/$lan_ip/g" package/base-files/files/bin/config_generate

echo "修改时区"
sed -i "s/'UTC'/'CST-8'\n   set system.@system[-1].zonename='$utc_name'/g" package/base-files/files/bin/config_generate

echo "修改默认主题"
sed -i 's/+luci-theme-bootstrap/+luci-theme-argon_new/g' feeds/luci/collections/luci/Makefile

echo "修改版本信息"
sed -i "s/R20.5.9/R20.5.9 By HFY166 Ver.$ver_name/g" package/lean/default-settings/files/zzz-default-settings
